config/routes.rb
Rails.application.routes.draw do


  root to: 'homes#top'
  get 'about' => 'homes#about'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }

  namespace :admins do
    resources :users, only:[:index, :show]
    resources :themes, only:[:index, :show, :destroy]
    resources :answers, only:[:index, :show, :destroy] do
      resources :comments, only:[:destroy]
    end
  end

  scope module: :public do
    resources :users, only:[:edit, :update, :show, :index]
    resources :relations, only: [:create, :destroy]
    get 'themes/rankindex' => 'themes#rankindex'
    get 'themes/random' => 'themes#random'
    get 'themes/introduction' => 'themes#introduction'
    resources :themes, only:[:index, :create, :new, :show]
    get 'answers/rankindex' => 'answers#rankindex'
    resources :answers, only:[:index, :create, :new, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :email, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :content, :user_id, :theme_id, presence: true

  belongs_to :theme
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :answer

  validates :content, :user_id, :answer_id, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :answer
  validates :user_id, :answer_id, presence: true
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :user

  # 画像のカラム名に合わせる
  attachment :image

  validates :image, :user_id, presence: true

  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    # 探してなければCreate。Passは変更されても大丈夫なようにランダム
    find_or_create_by!(email: 'guest@example.com', name: 'ゲスト', unique_code: 'guestlogin') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要!
    end
  end

  has_many :themes, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  # foreign_key: 'user_id'が省略されている
  has_many :relations
  # followingsモデルを命名して、実際はRelationモデル※自分がフォローしている人
  has_many :followings, through: :relations, source: :follow
  # （1行目の逆)
  has_many :reverse_of_relations, class_name: 'Relation', foreign_key: 'follow_id'
  # followersモデルを命名※自分をフォローしている人
  has_many :followers, through: :reverse_of_relations, source: :user

  def follow(other_user)
    unless self == other_user
      self.relations.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relation = self.relations.find_by(follow_id: other_user.id)
    relation.destroy if relations
  end
User
  def following?(other_user)
    self.followings.include?(other_user)
  end



  validates :name, :unique_code, :email, presence: true
  validates :name, length: { minimum: 2, maximum: 20}
  validates :unique_code, uniqueness: true
  # 5-12文字の半角英数字
  validates :unique_code, format: { with: /\A[a-z0-9]+\z/i,message: "は半角英数字である必要があります"}
  validates :unique_code, length: { minimum: 5, maximum: 12}


  attachment :profile_image
end

app/controllers/admins/answers_controller.rb
class Admins::AnswersController < ApplicationController
  def index
    @answers = Answer.page(params[:page]).reverse_order
  end

  def show
    @answer = Answer.find(params[:id])
    @theme = @answer.theme
  end

  def destroy
    answer = Answer.find(params[:id])
    answer.destroy
    redirect_to admins_answers_path
  end
end

app/controllers/admins/comments_controller.rb
class Admins::CommentsController < ApplicationController
  def destroy
    Comment.find_by(id: params[:id], answer_id: params[:answer_id]).destroy
    redirect_to admins_answer_path(params[:answer_id])
  end
end

app/controllers/admins/themes_controller.rb
class Admins::ThemesController < ApplicationController
  def index
    @themes = Theme.page(params[:page]).reverse_order
  end

  def show
    @theme = Theme.find(params[:id])
    @answers = @theme.answers.page(params[:page]).reverse_order
  end

  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy
    redirect_to admins_themes_path
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @answers = @user.answers.page(params[:page]).reverse_order

    # ユーザーが持つ全投稿のいいね合計
    @favorites_count = 0
    @answers.each do |answer|
      @favorites_count += answer.favorites.count
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :unique_code])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/answers_helper.rb
module Admins::AnswersHelper
end

app/helpers/admins/comments_helper.rb
module Admins::CommentsHelper
end

app/helpers/admins/themes_helper.rb
module Admins::ThemesHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/answers/_list.html.erb
<% answers.each do |answer| %>

<%= link_to admins_theme_path(answer.theme.id) do %>
<%= attachment_image_tag answer.theme, :image %>
<% end %>


<h1>
  <%= link_to admins_answer_path(answer.id) do %>
  <%= answer.content %>
  <% end %>
</h1>
<p>回答by:
<%= link_to admins_user_path(answer.user.id) do %>
<%= answer.user.name %>
<% end %>
</p>

<div>
<%= link_to "この回答を削除", admins_answer_path(answer), method: :delete %>
</div>

<p><%= link_to "#{answer.comments.count} コメント", admins_answer_path(answer.id) %></p>

<% end %>
<%= paginate answers %>

app/views/admins/answers/index.html.erb
<h2>回答一覧</h2>

<%= render 'admins/answers/list', answers: @answers %>

app/views/admins/answers/show.html.erb
<h1>回答詳細</h1>
<%= attachment_image_tag @theme, :image %>
<p>お題by:<%= @theme.user.name %></p>

<h1><%= @answer.content %></h1>
<p>ヒトコトby:<%= @answer.user.name %></p>

    <%= link_to "この回答を削除", admins_answer_path, method: :delete %>

<p>コメント件数：<%= @answer.comments.count %></p>
<% @answer.comments.each do |comment| %>
  <%= comment.user.name %>

  <div>
  <p><%= comment.created_at.strftime('%Y/%m/%d') %><br>
  <%= comment.content %></p>
  </div>

    <div>
    <%= link_to "このコメントを削除", admins_answer_comment_path(comment.answer, comment), method: :delete %>
    </div>
  <% end %>

app/views/admins/comments/destroy.html.erb
<h1>Admins::Comments#destroy</h1>
<p>Find me in app/views/admins/comments/destroy.html.erb</p>

app/views/admins/themes/_list.html.erb
<% themes.each do |theme| %>

  <%= link_to admins_theme_path(theme.id) do %>
  <%= attachment_image_tag theme, :image %>
  <% end %>

  <p>お題by:
  <%= link_to admins_user_path(theme.user.id) do %>
  <%= theme.user.name %>
  <% end %>
  </p>

  <p>回答数:
  <%= link_to admins_theme_path(theme.id) do %>
  <%= theme.answers.count %>
  <% end %>
  </p>

<div>
<%= link_to "このお題を削除", admins_theme_path(theme), method: :delete %>
</div>

<% end %>

<%= paginate themes %>

app/views/admins/themes/index.html.erb
<h2>お題一覧</h2>


<%= render 'admins/themes/list', themes: @themes %>

app/views/admins/themes/show.html.erb
<h1>お題詳細</h1>
<%= attachment_image_tag @theme, :image %>
<p>お題by:<%= @theme.user.name %></p>

<div>
<%= link_to "このお題を削除", admins_theme_path(@theme), method: :delete %>
</div>

<!--そのお題の回答一覧-->
  <%= render 'admins/answers/list', answers: @answers %>