config/routes.rb
Rails.application.routes.draw do


  root to: 'homes#top'
  get 'about' => 'homes#about'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }

  namespace :admins do
    resources :users, only:[:index, :show]
    resources :themes, only:[:index, :show, :destroy]
    resources :answers, only:[:index, :show, :destroy] do
      resources :comments, only:[:destroy]
    end
  end

  scope module: :public do
    resources :users, only:[:edit, :update, :show, :index]
    resources :relations, only: [:create, :destroy]
    get 'themes/rankindex' => 'themes#rankindex'
    get 'themes/random' => 'themes#random'
    get 'themes/introduction' => 'themes#introduction'
    resources :themes, only:[:index, :create, :new, :show]
    get 'answers/rankindex' => 'answers#rankindex'
    resources :answers, only:[:index, :create, :new, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :email, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :content, :user_id, :theme_id, presence: true

  belongs_to :theme
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :answer

  validates :content, :user_id, :answer_id, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :answer
  validates :user_id, :answer_id, presence: true
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :user

  # 画像のカラム名に合わせる
  attachment :image

  validates :image, :user_id, presence: true

  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    # 探してなければCreate。Passは変更されても大丈夫なようにランダム
    find_or_create_by!(email: 'guest@example.com', name: 'ゲスト', unique_code: 'guestlogin') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要!
    end
  end

  has_many :themes, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  # foreign_key: 'user_id'が省略されている
  has_many :relations
  # followingsモデルを命名して、実際はRelationモデル※自分がフォローしている人
  has_many :followings, through: :relations, source: :follow
  # （1行目の逆)
  has_many :reverse_of_relations, class_name: 'Relation', foreign_key: 'follow_id'
  # followersモデルを命名※自分をフォローしている人
  has_many :followers, through: :reverse_of_relations, source: :user

  def follow(other_user)
    unless self == other_user
      self.relations.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relation = self.relations.find_by(follow_id: other_user.id)
    relation.destroy if relations
  end
User
  def following?(other_user)
    self.followings.include?(other_user)
  end



  validates :name, :unique_code, :email, presence: true
  validates :name, length: { minimum: 2, maximum: 20}
  validates :unique_code, uniqueness: true
  # 5-12文字の半角英数字
  validates :unique_code, format: { with: /\A[a-z0-9]+\z/i,message: "は半角英数字である必要があります"}
  validates :unique_code, length: { minimum: 5, maximum: 12}


  attachment :profile_image
end

app/controllers/admins/answers_controller.rb
class Admins::AnswersController < ApplicationController
  def index
    @answers = Answer.page(params[:page]).reverse_order
  end

  def show
    @answer = Answer.find(params[:id])
    @theme = @answer.theme
  end

  def destroy
    answer = Answer.find(params[:id])
    answer.destroy
    redirect_to admins_answers_path
  end
end

app/controllers/admins/themes_controller.rb
class Admins::ThemesController < ApplicationController
  def index
    @themes = Theme.page(params[:page]).reverse_order
  end

  def show
    @theme = Theme.find(params[:id])
    @answers = @theme.answers.page(params[:page]).reverse_order
  end

  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy
    redirect_to admins_themes_path
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @answers = @user.answers.page(params[:page]).reverse_order

    # ユーザーが持つ全投稿のいいね合計
    @favorites_count = 0
    @answers.each do |answer|
      @favorites_count += answer.favorites.count
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :unique_code])
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/answers_helper.rb
module Admins::AnswersHelper
end

app/helpers/admins/comments_helper.rb
module Admins::CommentsHelper
end

app/helpers/admins/themes_helper.rb
module Admins::ThemesHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messeages.html.erb
    <% if resource.errors.any? %>
     <div>
       <h2>Error</h2>
        <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
     </div>
   <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuzzSeed</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <meta name="viewport" content="width=device-width,initial-scale=1.0">
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/9c0bf09418.js" crossorigin="anonymous"></script>
  </head>
<header class="shadow-sm sticky-top w-100">
  <nav class="navbar navbar-expand-lg navbar-light">
    <body>
      <div class="container">
        <a class="navbar-brand" href="/"><%= image_tag('logo.png') %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav pt-5 ml-auto">
            <% if user_signed_in? %>
             <li class="nav-item ml-4 h4">
               <%= link_to 'ヒトコト', answers_path %>
             </li>
             <li class="nav-item ml-4 h4">
               <%= link_to 'お題', themes_path %>
             </li>
             <li class="nav-item ml-4 h3">
               <%= link_to destroy_user_session_path, method: :delete do %>
               <i class="fas fa-sign-out-alt"></i>
               <% end %>
             </li>
             <li class="nav-item ml-4 h4">
               <%= link_to user_path(current_user) do %>
               <%= attachment_image_tag current_user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: "40x40", class:"rounded-circle"; %>
               <% end %>
             </li>
           <% elsif admin_signed_in? %>
            <p>管理者ログイン中です</p>
            <li class="nav-item">
              <%= link_to 'お題一覧', admins_themes_path %>
            </li>
            <li class="nav-item">
              <%= link_to '回答一覧', admins_answers_path %>
            </li>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', admins_users_path %>
            </li>
            <li class="nav-item">
              <%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "about", about_path %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path %>
            </li>
            <li class="nav-item">
              <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %>
            </li>
            <li class="nav-item">
              <%= link_to "管理者新規登録", new_admin_registration_path %>
            </li>
            <li class="nav-item">
              <%= link_to "管理者ログイン", new_admin_session_path %>
           </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
  <% if notice.present? %>
    <h3><%= flash[:notice] %></h3>
  <% end %>
  <% if alert.present? %>
    <h3><%= flash[:alert] %></h3>
  <% end %>
  <%= yield %>

<footer class="mt-5 pt-5">
<div>
  <%= link_to "管理者ログイン", new_admin_session_path, class:"text-white"; %>
</div>
</footer>

   </body>
</html>